spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: fedFaxe

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 1 day in milliseconds

amadeus:
  api-key: ${AMADEUS_API_KEY}
  api-secret: ${AMADEUS_API_SECRET}

app:
  backend:
    url: http://localhost:8087
