###port information
spring.application.name=fedFaxe
server.port=8087

# Allow external connections
server.address=0.0.0.0

server.forward-headers-strategy=native

aws.accessKey=YOUR_ACCESS_KEY
aws.secretKey=YOUR_SECRET_KEY
aws.region=us-east-1
aws.s3.bucket=fedfaxebucket--use1-az6--x-s3